### ISSUE TITLE
qualified names   (package::FUN())

### ISSUE THREAD

**Issue by jimrothstein** [kbmorales/PPP#1]
Not a biggie, but R-pkg book, Ch 6 and Ch 13.6.1 [recommends:](https://r-pkgs.org/package-within.html#delta-an-attempt-at-a-package)

`All of our calls to tidyverse functions have now been qualified with the name of the specific package that actually provides the function, e.g. dplyr::mutate(). There are other ways to access functions in another package, explained in chapter 13, but this is our recommended default. It is also our strong recommendation that no one depend on the tidyverse meta-package in a package10. Instead, it is better to identify the specific package(s) you actually use. In this case, our package only uses dplyr.`

**Comment by kbmorales** [comment]
Does this pertain to particular lines of code you can point to or some error in the namespace? I am unsure what this issue is referencing.

**Comment by jimrothstein** [comment]
Example (from clean.R)

Now:   
adbs <- map_df(csv_files,

Suggest:
adbs <- purrr::map_df(csv_files,

**Comment by kbmorales** [comment]
Closing this as it's been resolved.
