### ISSUE TITLE
ppp_assemble(version = 1) --- crash!

### ISSUE THREAD

**Issue by jimrothstein** [kbmorales/PPP#2]
Runs.  
But no error, just no data.
Nor are the data directories set up.

(Have not traced through code yet).

I mostly use vanilla terminal, nvim and without any interface

**Comment by kbmorales** [comment]
Did you run ppp_collect() first to download the data?
Can you post your traceback?

**Comment by jimrothstein** [comment]
Let me run your latest changes (from today, 9/14/2020) and report back here:

**Update 1:   ppp_collect() working fine.**

- pulled your latest  work;  created local branch for my work.
- load_all()
- ran ppp_collect(version=1)

**Update 2:   ppp_collect() works fine, with build()**

- restart R
- build() and installed() package on my local machine
- restart R
- again ran ppp_collect(version=1), works great.

**Update 3:  ppp_assemble(version = 1)  --- crash!**

- appears to be working fine,  gets to at least loan "mid-point"
- R crashes (I use neovim/nvim-R plugin and have reported the error)
- I do not see any R error b/c the plugin and terminal all crash.
- can try Rstudio (haven't used in awhile)

**Comment by jimrothstein** [comment]
**Update 4:   Plug-in author suggests I run C debugger**
-  Not sure I want to go the debugger path.
-   You are using RSTUDIO?   and no problems running ppp_assemble() ?
-    I will give this a try.

**Comment by jimrothstein** [comment]
**Update 5: Rstudio also crashes**

-dialog box: R Session Aborted; Fatal error; Session was terminated.
-Last cat message:  Creating midpoint loan value  LoanRangeMin.

**Comment by kbmorales** [comment]
Was just requesting a traceback, no need to run a C debugger. But that won't help with this issue, as my suspicion is that this is a RAM issue. The resulting R object is very large and if your computer can't handle storing that in RAM it'll crash your session. Unfortunately, there is no way around this, but I can add a warning before the user proceeds with the read in functions.

**Comment by jimrothstein** [comment]
You are probably right:    I use a Chromebook.   Suggestions where I might still be able to help out?

**Comment by kbmorales** [comment]
I'll close this issue then, but thanks for bringing to light that this package has some RAM requirements due to the size of the data being so large.

Re: help, I'll open a separate issue and tag you on it there!
